//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrator
    {
        public string userName { get; set; }
        public string password { get; set; }
        public string createdBy { get; set; }
        public string createdTime { get; set; }
    }
}
