//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timekeeping
    {
        public int id { get; set; }
        public Nullable<int> employeeID { get; set; }
        public string date { get; set; }
        public string timeIn { get; set; }
        public string timeOut { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
